Credit and authorship of this script goes to:
https://www.kaggle.com/thomasnelson/working-with-dna-sequence-data-for-ml

#### Biopython (Bio) is one library for working with sequences (DNA,RNA,protein,etc) in python

In [11]:
from Bio import SeqIO
import numpy as np
import re

#### It's easy to load sequences and their IDs with the SeqIO.parse function

In [13]:
count = 0
for seq_record in SeqIO.parse('GCA_000009225.1_ASM922v1_cds_from_genomic.fa', "fasta"):
    print(seq_record)
#     print(seq_record.id)
#     print(seq_record.seq)

ID: lcl|AM181176.4_cds_CAJ57270.1_1
Name: lcl|AM181176.4_cds_CAJ57270.1_1
Description: lcl|AM181176.4_cds_CAJ57270.1_1 [gene=dnaA] [locus_tag=PFLU_0001] [db_xref=EnsemblGenomes-Gn:PFLU_0001,EnsemblGenomes-Tr:CAJ57270,GOA:B0B0A5,InterPro:IPR001957,InterPro:IPR003593,InterPro:IPR010921,InterPro:IPR013159,InterPro:IPR013317,InterPro:IPR018312,InterPro:IPR020591,InterPro:IPR024633,InterPro:IPR027417] [protein=chromosomal replication initiator protein DnaA] [protein_id=CAJ57270.1] [location=1..1506] [gbkey=CDS]
Number of features: 0
Seq('GTGTCAGTGGAACTTTGGCAGCAGTGCGTGGAGCTTTTGCGCGATGAGCTGCCT...TGA')
ID: lcl|AM181176.4_cds_CAY46287.1_2
Name: lcl|AM181176.4_cds_CAY46287.1_2
Description: lcl|AM181176.4_cds_CAY46287.1_2 [gene=dnaN] [locus_tag=PFLU_0002] [db_xref=EnsemblGenomes-Gn:PFLU_0002,EnsemblGenomes-Tr:CAY46287,GOA:C3KDU3,InterPro:IPR001001,InterPro:IPR022634,InterPro:IPR022635,InterPro:IPR022637,UniProtKB/TrEMBL:C3KDU3] [protein=DNA polymerase III, beta chain] [protein_id=CAY46287.1] [loc

ID: lcl|AM181176.4_cds_CAY48143.1_1855
Name: lcl|AM181176.4_cds_CAY48143.1_1855
Description: lcl|AM181176.4_cds_CAY48143.1_1855 [locus_tag=PFLU_1898] [db_xref=EnsemblGenomes-Gn:PFLU_1898,EnsemblGenomes-Tr:CAY48143,GOA:C3K505,InterPro:IPR004695,UniProtKB/TrEMBL:C3K505] [protein=putative transport related membrane protein] [protein_id=CAY48143.1] [location=2072409..2073578] [gbkey=CDS]
Number of features: 0
Seq('ATGAGTGATACACGACTCGCAGCGATTATGGGCGGCAGCCATCCACTGGCAGCA...TGA')
ID: lcl|AM181176.4_cds_CAY48144.1_1856
Name: lcl|AM181176.4_cds_CAY48144.1_1856
Description: lcl|AM181176.4_cds_CAY48144.1_1856 [locus_tag=PFLU_1899] [db_xref=EnsemblGenomes-Gn:PFLU_1899,EnsemblGenomes-Tr:CAY48144,InterPro:IPR005122,UniProtKB/TrEMBL:C3K506] [protein=conserved hypothetical protein] [protein_id=CAY48144.1] [location=complement(2073587..2074195)] [gbkey=CDS]
Number of features: 0
Seq('TTGTCAGTGTCGACTCACCAAGGCACCGCCCCCCTCGGGATTTCGCTTGAAGCG...TAG')
ID: lcl|AM181176.4_cds_CAY48145.1_1857
Name: lcl|AM181176.

Seq('ATGCCAACCCTGCATCTGCTCTGCGGCAAGATCGCCTCGGGCAAGTCCACGCTC...TGA')
ID: lcl|AM181176.4_cds_CAY49654.1_3355
Name: lcl|AM181176.4_cds_CAY49654.1_3355
Description: lcl|AM181176.4_cds_CAY49654.1_3355 [locus_tag=PFLU_3430] [db_xref=EnsemblGenomes-Gn:PFLU_3430,EnsemblGenomes-Tr:CAY49654,GOA:C3KD81,InterPro:IPR004601,InterPro:IPR013022,UniProtKB/TrEMBL:C3KD81] [protein=conserved hypothetical protein] [protein_id=CAY49654.1] [location=complement(3798701..3799732)] [gbkey=CDS]
Number of features: 0
Seq('ATGACTCATCCTCGCATCGGCTTTGCATGCCAGTACAAGCATCCCGAACGCCTG...TGA')
ID: lcl|AM181176.4_cds_CAY49655.1_3356
Name: lcl|AM181176.4_cds_CAY49655.1_3356
Description: lcl|AM181176.4_cds_CAY49655.1_3356 [locus_tag=PFLU_3431] [db_xref=EnsemblGenomes-Gn:PFLU_3431,EnsemblGenomes-Tr:CAY49655,InterPro:IPR016923,InterPro:IPR019251,UniProtKB/TrEMBL:C3KCE0] [protein=putative membrane protein] [protein_id=CAY49655.1] [location=3799907..3800320] [gbkey=CDS]
Number of features: 0
Seq('ATGACTACCCTTCCCGCTTACCGATACACACCC

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [76]:
example_seq = str(seq_record.seq)
example_seq

'ATGAAACGTACTTTCCAACCAAGCACCATCAAACGCGCCCGCACCCACGGTTTCCGTGCTCGCATGGCTACCAAGAACGGCCGTGCTGTCCTGTCGCGTCGTCGCGCCAAAGGTCGTGCGCGTCTGGCAGTTTGA'

#### 3 approaches for sequence to vector embedding. 1) encode the sequence information as an ordinal vector and work with that directly, 2) one-hot encode the sequence letters and use the resulting array and 3) treat the DNA sequence as a language (text) and use various "language" processing methods.

#### Ordinal encoding

In [59]:
# A,T,C,G becomes 0.25,0.5,0.75,1.0, respectively.
# if there is an "N" because the base is uncertain, we will assign it to 0.0
def str_to_arr(seq):
    '''convert DNA sequence to numpy array'''
    seq = seq.lower()
    seq = re.sub('[^acgt]', 'z', seq)
    arr = np.array(list(seq))
    return arr

# create a label encoder with 'acgtn' alphabetx
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder();
label_encoder.fit(np.array(['a','c','g','t','z']));

def ordinal_encoder(arr):
    ''' function to encode a DNA sequence string as an ordinal vector.
     returns a numpy array with a=0.25, c=0.50, g=0.75, t=1.00, n=0.00'''
    integer_encoded = label_encoder.transform(arr)
    float_encoded = integer_encoded.astype(float)
    float_encoded[float_encoded == 0] = 0.25 # A
    float_encoded[float_encoded == 1] = 0.50 # C
    float_encoded[float_encoded == 2] = 0.75 # G
    float_encoded[float_encoded == 3] = 1.00 # T
    float_encoded[float_encoded == 4] = 0.00 # anything else, z
    return float_encoded

ordinal_encoder(str_to_arr(example_seq))

array([0.25, 1.  , 0.75, 0.25, 0.25, 0.25, 0.5 , 0.75, 1.  , 0.25, 0.5 ,
       1.  , 1.  , 1.  , 0.5 , 0.5 , 0.25, 0.25, 0.5 , 0.5 , 0.25, 0.25,
       0.75, 0.5 , 0.25, 0.5 , 0.5 , 0.25, 1.  , 0.5 , 0.25, 0.25, 0.25,
       0.5 , 0.75, 0.5 , 0.75, 0.5 , 0.5 , 0.5 , 0.75, 0.5 , 0.25, 0.5 ,
       0.5 , 0.5 , 0.25, 0.5 , 0.75, 0.75, 1.  , 1.  , 1.  , 0.5 , 0.5 ,
       0.75, 1.  , 0.75, 0.5 , 1.  , 0.5 , 0.75, 0.5 , 0.25, 1.  , 0.75,
       0.75, 0.5 , 1.  , 0.25, 0.5 , 0.5 , 0.25, 0.25, 0.75, 0.25, 0.25,
       0.5 , 0.75, 0.75, 0.5 , 0.5 , 0.75, 1.  , 0.75, 0.5 , 1.  , 0.75,
       1.  , 0.5 , 0.5 , 1.  , 0.75, 1.  , 0.5 , 0.75, 0.5 , 0.75, 1.  ,
       0.5 , 0.75, 1.  , 0.5 , 0.75, 0.5 , 0.75, 0.5 , 0.5 , 0.25, 0.25,
       0.25, 0.75, 0.75, 1.  , 0.5 , 0.75, 1.  , 0.75, 0.5 , 0.75, 0.5 ,
       0.75, 1.  , 0.5 , 1.  , 0.75, 0.75, 0.5 , 0.25, 0.75, 1.  , 1.  ,
       1.  , 0.75, 0.25])

#### One-hot encoding of DNA sequence

In [79]:
from sklearn.preprocessing import OneHotEncoder
def one_hot_encoder(arr):
    '''return an Nx4 matrix where N is the length of the sequence.'''
    integer_encoded = label_encoder.transform(arr)
    onehot_encoder = OneHotEncoder(sparse=False,dtype=int,categories=[range(4)])
    integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
    onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
#     onehot_encoded = np.delete(onehot_encoded, -1, 1)
    return onehot_encoded

one_hot_encoder(str_to_arr(example_seq))

array([[1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 1,

#### Treating DNA sequence as a "language", otherwise known as k-mer counting
Both one-hot encoding and ordinal vectors are not ideal for classification or regression because sequences of differing lengths will produce a matrix or vector of varying length (can pad with zeros or truncate and still have it be useful) 

The sequence language analogy: genome as the book, subsequences (genes and gene families) are sentences and chapters, k-mers and peptides (motifs) are words, and nucleotide bases and amino acids are the alphabet. Since the analogy seems so apt, it stands to reason that the amazing work done in the natural language processing field should also apply to the natural language of DNA and protein sequences.

First take the long biological sequence and break it down into k-mer length overlapping “words”. For example, if the "words" are of length 6 (hexamers), “ATGCATGCA” becomes: ‘ATGCAT’, ‘TGCATG’, ‘GCATGC’, ‘CATGCA’. Hence our example sequence is broken down into 4 hexamer words. This "word" length is a hyperparameter that can be tuned

In genomics, these types of manipulations aka "k-mer counting", or counting the occurences of each possible k-mer sequence. 

In [83]:
def getKmers(sequence, size):
    '''convert sequence to overlapping k-mer "words" '''
    return [sequence[x:x+size].lower() for x in range(len(sequence) - size + 1)]
getKmers(example_seq,6)

['atgaaa',
 'tgaaac',
 'gaaacg',
 'aaacgt',
 'aacgta',
 'acgtac',
 'cgtact',
 'gtactt',
 'tacttt',
 'actttc',
 'ctttcc',
 'tttcca',
 'ttccaa',
 'tccaac',
 'ccaacc',
 'caacca',
 'aaccaa',
 'accaag',
 'ccaagc',
 'caagca',
 'aagcac',
 'agcacc',
 'gcacca',
 'caccat',
 'accatc',
 'ccatca',
 'catcaa',
 'atcaaa',
 'tcaaac',
 'caaacg',
 'aaacgc',
 'aacgcg',
 'acgcgc',
 'cgcgcc',
 'gcgccc',
 'cgcccg',
 'gcccgc',
 'cccgca',
 'ccgcac',
 'cgcacc',
 'gcaccc',
 'caccca',
 'acccac',
 'cccacg',
 'ccacgg',
 'cacggt',
 'acggtt',
 'cggttt',
 'ggtttc',
 'gtttcc',
 'tttccg',
 'ttccgt',
 'tccgtg',
 'ccgtgc',
 'cgtgct',
 'gtgctc',
 'tgctcg',
 'gctcgc',
 'ctcgca',
 'tcgcat',
 'cgcatg',
 'gcatgg',
 'catggc',
 'atggct',
 'tggcta',
 'ggctac',
 'gctacc',
 'ctacca',
 'taccaa',
 'accaag',
 'ccaaga',
 'caagaa',
 'aagaac',
 'agaacg',
 'gaacgg',
 'aacggc',
 'acggcc',
 'cggccg',
 'ggccgt',
 'gccgtg',
 'ccgtgc',
 'cgtgct',
 'gtgctg',
 'tgctgt',
 'gctgtc',
 'ctgtcc',
 'tgtcct',
 'gtcctg',
 'tcctgt',
 'cctgtc',
 'ctgtcg',

In [87]:
# the "words" can be joined into a "sentence" and fed into NLP methods. 
words = getKmers(example_seq, size=6)
sentence = ' '.join(words)
sentence
# if the words are hexamers (length 6) and the alphabet has 4 elements, then there are 4^6 = 4096 possible words of length 6

'atgaaa tgaaac gaaacg aaacgt aacgta acgtac cgtact gtactt tacttt actttc ctttcc tttcca ttccaa tccaac ccaacc caacca aaccaa accaag ccaagc caagca aagcac agcacc gcacca caccat accatc ccatca catcaa atcaaa tcaaac caaacg aaacgc aacgcg acgcgc cgcgcc gcgccc cgcccg gcccgc cccgca ccgcac cgcacc gcaccc caccca acccac cccacg ccacgg cacggt acggtt cggttt ggtttc gtttcc tttccg ttccgt tccgtg ccgtgc cgtgct gtgctc tgctcg gctcgc ctcgca tcgcat cgcatg gcatgg catggc atggct tggcta ggctac gctacc ctacca taccaa accaag ccaaga caagaa aagaac agaacg gaacgg aacggc acggcc cggccg ggccgt gccgtg ccgtgc cgtgct gtgctg tgctgt gctgtc ctgtcc tgtcct gtcctg tcctgt cctgtc ctgtcg tgtcgc gtcgcg tcgcgt cgcgtc gcgtcg cgtcgt gtcgtc tcgtcg cgtcgc gtcgcg tcgcgc cgcgcc gcgcca cgccaa gccaaa ccaaag caaagg aaaggt aaggtc aggtcg ggtcgt gtcgtg tcgtgc cgtgcg gtgcgc tgcgcg gcgcgt cgcgtc gcgtct cgtctg gtctgg tctggc ctggca tggcag ggcagt gcagtt cagttt agtttg gtttga'

In [88]:
mySeq2 = 'GATGGCCATCCCCGCCCGAGCGGGGGGGG'
mySeq3 = 'CATGGCCATCCCCGCCCGAGCGGGCGGGG'
sentence2 = ' '.join(getKmers(mySeq2, size=6))
sentence3 = ' '.join(getKmers(mySeq3, size=6))

In [98]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform([sentence, sentence2, sentence3]).toarray() # counts of hexamers in the vocabulary

In [99]:
X

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
        1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 2, 1, 0, 1, 1, 1, 1, 2, 2, 1, 0,
        0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
        1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 3,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,